# local

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/megavnc
    username: megavncuser
    password: "!mb220719"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

#### 스키마 생성용
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
