# dev

server:
  port: 8443

  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: "!mb220719"

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.34:5432/megavnc
    username: megavncuser
    password: "!mb220719"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
