# local

server:
  port: 8443
  servlet:
    session:
      timeout: 60m
  ssl:
    key-store: keystore.p12
    key-store-password: "!mb220719"
    key-store-type: PKCS12

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/megavnc
    username: megavncuser
    password: "!mb220719"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
jwt:


tcp:
  server:
    port: 2002

#### 스키마 생성용
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
