# local

server:
  port: 8443
  servlet:
    session:
      timeout: 60m
  ssl:
    key-store: classpath:megabridge.keystore
    key-store-password: "!mb220719"
    key-store-type: PKCS12

fileKey: asd8g9dqyfeg1ohndsawd0hqidnw

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    url: jdbc:postgresql://192.168.0.22:5432/megavnc
    username: megavncuser
    password: "!mb220719"
  thymeleaf:
    prefix: classpath:/templates/


cron:
  expression: "0 0 9 * * ?"    #매일 오래된 로그가 삭제되는 시각
log:
  retention:
    days: 30                   #로그가 보관되는 날짜




