CREATE SEQUENCE IF NOT EXISTS member_group_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS member_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS remote_pc_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS segment_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE access_logs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp    TIMESTAMP WITHOUT TIME ZONE,
    group_name   VARCHAR(255),
    pc_name      VARCHAR(255),
    division     VARCHAR(255),
    reconnect_id VARCHAR(255),
    ip           VARCHAR(255),
    CONSTRAINT pk_accesslogs PRIMARY KEY (id)
);

CREATE TABLE error_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    class_name  VARCHAR(255),
    line_number INTEGER                                 NOT NULL,
    message     VARCHAR(1000),
    CONSTRAINT pk_errorlogs PRIMARY KEY (id)
);

CREATE TABLE file_info
(
    seq          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    file_name    VARCHAR(255),
    file_path    VARCHAR(255),
    file_size    BIGINT,
    reconnect_id VARCHAR(255),
    CONSTRAINT pk_fileinfo PRIMARY KEY (seq)
);

CREATE TABLE member
(
    id         BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    password   VARCHAR(255),
    role       VARCHAR(255),
    username   VARCHAR(255),
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE member_group
(
    id        BIGINT NOT NULL,
    member_id BIGINT,
    group_id  BIGINT,
    CONSTRAINT pk_member_group PRIMARY KEY (id)
);

CREATE TABLE remote_pc
(
    id              BIGINT NOT NULL,
    repeater_id     BIGINT,
    name            VARCHAR(255),
    assigned_at     TIMESTAMP WITHOUT TIME ZONE,
    status          VARCHAR(255),
    access_password VARCHAR(255),
    reconnect_id    VARCHAR(255),
    group_id        BIGINT,
    CONSTRAINT pk_remote_pc PRIMARY KEY (id)
);

CREATE TABLE segment
(
    id         BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    group_name VARCHAR(255),
    CONSTRAINT pk_segment PRIMARY KEY (id)
);

ALTER TABLE file_info
    ADD CONSTRAINT uc_fileinfo_filename UNIQUE (file_name);

ALTER TABLE member
    ADD CONSTRAINT uc_member_username UNIQUE (username);

ALTER TABLE remote_pc
    ADD CONSTRAINT uc_remote_pc_repeaterid UNIQUE (repeater_id);

ALTER TABLE segment
    ADD CONSTRAINT uc_segment_groupname UNIQUE (group_name);

ALTER TABLE member_group
    ADD CONSTRAINT FK_MEMBER_GROUP_ON_GROUP FOREIGN KEY (group_id) REFERENCES segment (id);

ALTER TABLE member_group
    ADD CONSTRAINT FK_MEMBER_GROUP_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE remote_pc
    ADD CONSTRAINT FK_REMOTE_PC_ON_GROUP FOREIGN KEY (group_id) REFERENCES segment (id);